### ISSUE TITLE
result  show below other element 

### ISSUE THREAD

**Issue by OrangeFlavoredColdCoffee** [mrlaessig/react-native-autocomplete-input#102]
![Uploading 1231531130458_.pic.jpg…]()

when style like image above , zIndex does not work

I think  the  view  level  not  reasonable

**Comment by OrangeFlavoredColdCoffee** [comment]
![1231531130458_ pic](https://user-images.githubusercontent.com/15223345/42444849-c8d7bd18-83a3-11e8-9f76-78b6612209a0.jpg)

**Comment by xstone93** [comment]
I had the same issue and fixed it by putting <Autocomplete> and the result into the same <View> and set zIndex: 1 at the autocomplete container:
<View>
  <Autocomplete
    containerStyle={{zIndex:1}}
  />
  <Result />
</View>
