### ISSUE TITLE
Transparent listview and not clickable on second and third item?

### ISSUE THREAD

**Issue by isaaclem** [mrlaessig/react-native-autocomplete-input#113]
![screen shot 2018-11-09 at 10 18 37 am](https://user-images.githubusercontent.com/32945572/48239177-e2c17280-e408-11e8-98b7-efdc6ca22595.png)

The rendered list seems to be semi transparent and second and third item are not clickable?

```
<Autocomplete
          autoCapitalize="none"
          autoCorrect={false}
          inputContainerStyle={{ borderWidth: 0 }}
          containerStyle={{ width: screenWidth, marginTop: 10, zIndex: 999 }}
          data={contacts.length === 1 && comp(value, contacts[0].field) ? [] : contacts}
          defaultValue={value}
          onChangeText={v => this.props.reduxAction({ prop: element, value: v })}
          placeholder="Enter Star Wars film title"
          renderItem={({ field }) => (
            <TouchableOpacity style={{ backgroundColor: 'yellow' }} onPress={() => this.props.reduxAction({ prop: element, value: field })}>
              <Text style={{}}>
                {field}
              </Text>
            </TouchableOpacity>
          )}
        />
```

**Comment by sooyang** [comment]
hey @isaaclem, I stumbled upon same issue as well. Are there any components below your `<AutoComplete/>` component? In my case I had a `<View/>` component below it and its somehow overlapping with the rendered list thus causing only the second or third item to be un-clickable. 

You can inspect the second and third element of the rendered list on your simulator to find out whether there are any overlapping of components.

**Comment by pingxiaodou** [comment]
add zIndex to the <View> where wrapped your Autocomplete element
