### ISSUE TITLE
On renderItem, impossible to click on TouchableOpacity 

### ISSUE THREAD

**Issue by gillesfabre34** [mrlaessig/react-native-autocomplete-input#115]
Hi everyone, I have a problem with this module.

My filter runs, the list of items is correctly shown when I enter some letters in the input field, but impossible to click on the TouchableOpacity : the onPress() event is never called.
In my code, the console.log('AAA) runs, but never the console('BBB')
Someone maybe encountered the same problem ? Any help would be great.

```
render() {
        const availableTreatmentNumbers = this.filterTreatmentNumbers(this.state.query)
        return (
            <View style={mainView.container }>
                <TopBarComponent title={I18n.t('TOP_BAR_DISPENSATION')} navigation={this.props.navigation}/>

                <View style={styleScanManualDispensation.textField}>
                <AutoComplete
                    autoCapitalize="none"
                    autoCorrect={false}
                    containerStyle={styleScanManualDispensation.autoCompleteContainer}
                    data={availableTreatmentNumbers}
                    defaultValue={this.state.query}
                    listStyle={styleScanManualDispensation.list}
                    onChangeText={text => this.setState({ query: text })}
                    placeholder={I18n.t('DISPENSATION_SCAN_MANUAL_TREATMENT_NUMBER')}
                    renderItem={(title) => {
                        console.log('AAA');
                         return (
                            <TouchableOpacity onPress={() => {
                                console.log('BBB');
                                this.setState({ query: title })
                            }} style={styleScanManualDispensation.touchableOpacity}>
                                <Text style={styleScanManualDispensation.itemText}>{title}</Text>
                            </TouchableOpacity>
                        )
                    }}
                />

                </View>
                <View style={styleScanManualDispensation.viewButtons}>
                    <View style={styleScanManualDispensation.startScanningButton}>
                        <ClassicButtonComponent
                            disabled={!this.state.isValidForm}
                            buttonContent={I18n.t('DONE')}
                            onPress={() => this.navigateToKit()}/>
                    </View>
                    <View style={styleScanManualDispensation.cancelButton}>
                        <CancelButtonComponent
                            disabled={false}
                            onPress={() => this.props.navigation.navigate('ScanDispensation')}/>
                    </View>
                </View>
            </View>
        );
    }
```

**Comment by gillesfabre34** [comment]
And here is my style file : 

```
import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    textField: {
        width: '100%',
        height: 120,
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginBottom: 0,
    },
    viewButtons: {
        width: '100%',
        justifyContent: 'center',
        flex: 1,
    },
    startScanningButton: {
        width: '100%',
        height: 100,
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    cancelButton: {
        width: '100%',
        height: 100,
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: 10
    },
    autoCompleteContainer: {
        marginLeft: 10,
        marginRight: 10,
        width: '80%',
    },
    itemText: {
        fontSize: 17,
        margin: 2
    },
    touchableOpacity: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    list: {
        height: 30,
    },
    descriptionContainer: {
        // `backgroundColor` needs to be set otherwise the
        // autocomplete input will disappear on text input.
        backgroundColor: '#F5FCFF',
        marginTop: 8
    },
});
```

**Comment by blabz-rahulmandalkar** [comment]
I have same issue

**Comment by PerraiD** [comment]
Up ! did you find a way ?

**Comment by saeedkargosha** [comment]
I have same issue.

**Comment by DNA-h** [comment]
In Android, you should put your Autocomplete inside a View with position: 'absolute' so that Autocomplete can print the list over other views, ALSO you should the parent View of Autocomplete should have a zIndex greater than the rest of your Views, otherwise, the click event is processed by the view which item is drawn over. here is a sample

`     <View
            style={{
              flexDirection: 'row',
              position: 'absolute',
              top: StatusBar.currentHeight,
              left: 0,
              right: 0,
              height: 80,
              marginHorizontal: 10,
              alignItems: 'center',
              zIndex: 2000,
            }}
          >
              <Autocomplete
                autoCapitalize='none'
                autoCorrect={false}
                containerStyle={styles.autocompleteContainer}
                inputContainerStyle={{ borderRadius: 10, overflow: 'hidden' }}
                onSubmitEditing={this.keyboardHide}
                data={this.state.focus ? this.state.searches.filter(this._compare) : []}
                onFocus={() => {
                  this.setState({ focus: true });
                }}
                onBlur={() => {
                  this.setState({ focus: false });
                }}
                defaultValue={this.state.query}
                onChangeText={text => {
                  this.setState({ query: text });
                }}
                placeholder='DNA-h'
                renderItem={({ item }) => (
                  <TouchableWithoutFeedback
                    key={item}
                    onPress={() => {
                      console.log('cliked');
                      this.setState({ query: item });
                      this.props.navigation.navigate('Home');
                    }}
                  >
                    <View>
                      <Text style={styles.itemText}>
                        {item}
                      </Text>
                    </View>
                  </TouchableWithoutFeedback>
                )}
              />
          </View>`

**Comment by mussaiin** [comment]
I tried to use TouchableHighlight instead and it worked for me

**Comment by ambessh** [comment]
set position:'absolute' and a higher zIndex to listStyle prop.
