### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by Javier-Rotelli** [mrlaessig/react-native-autocomplete-input#124]
Hey @mrlaessig  looks like you haven't been around this project in a while. do you still plan to maintain it?
i'd be interested in merging a few of the PR's. how can we work to make that happen?

**Comment by mrlaessig** [comment]
@Javier-Rotelli send you an invite to be a project collaborator.

**Comment by Javier-Rotelli** [comment]
Thanks! will be merging PR's soon :D
