### ISSUE TITLE
Open Suggestion List above TextInput

### ISSUE THREAD

**Issue by vikrantnegi** [mrlaessig/react-native-autocomplete-input#131]
Is there a way to open the suggestion list on the top of the input box?

This works if the input box is on the top but for the input boxes near the bottom, the list gets hidden behind the keyboard. 

Best case scenario would be to detect the position of the input or maybe available space and then open the suggestion list accordingly. 

Thanks.

**Comment by EdwinJDiaz** [comment]
+1

**Comment by galbenyosef** [comment]
Hello,
have you tried "re-ordering JSX" ? 
I faced something similiar, this helped me:
[https://github.com/facebook/react-native/issues/1076](url)
In a short, 'column-reverse' your parent View, then re order sibling (turn them upside down)
