### ISSUE TITLE
Unable to view suggestions in list on renderItem

### ISSUE THREAD

**Issue by neilharia7** [mrlaessig/react-native-autocomplete-input#132]
Hi, 

I have implemented autocomplete component, on text change I can see the a list of text in android as expected, but on iOS the list appears without any text.

    findOrgName(orgName) {
		if (orgName === '') {
			return [];
		}

		const list = data_dropdown;
		const regex = new RegExp(`${orgName}`, 'i');
		return list.filter(data => data.org.search(regex) >= 0);
	}

    render() {
         	const {orgName} = this.state;
		const list = this.findOrgName(orgName);
		const compute = (a, b) => a.toLowerCase() == b.toLowerCase();
		const finalData = list.length === 1 && compute(orgName, list[0].org) ? [] : list;
		
		<Autocomplete
			style={orgName == '' ? {
				borderColor: DISABLED_TEXT,
				backgroundColor: '#FFFFFF',
				borderRadius: 5,
				borderWidth: 0.5,
				paddingLeft: 16,
				height: IO_FIELD_HEIGHT,
				fontFamily: FONT_FAMILY_MEDIUM,
				fontSize: MEDIUM_FONT,
			}
			: {
				borderColor: DISABLED_TEXT,
				backgroundColor: '#FFFFFF',
				borderBottomColor: DARK_GRAY,
				borderRadius: 5,
				borderWidth: 0.5,
				paddingLeft: 16,
				height: IO_FIELD_HEIGHT,
				fontFamily: FONT_FAMILY_MEDIUM,
				fontSize: MEDIUM_FONT,
			}}
			inputContainerStyle={{
				borderColor: '#FFFFFF',
				backgroundColor: '#FFFFFF',
				borderRadius: 5,
				borderWidth: 0.5,
				height: IO_FIELD_HEIGHT,
				fontFamily: FONT_FAMILY_MEDIUM,
				fontSize: MEDIUM_FONT,
			}}
			listStyle={{position: 'relative'}}
			data={finalData}
			defaultValue={orgName}
			onChangeText={(text) => {this.setState({orgName: text})}}
			placeholder={devEnv.professionalDetails.organizationNamePlaceholder}
			placeholderTextColor={DISABLED_TEXT}
			placeholderStyle={{fontFamily: FONT_FAMILY_MEDIUM, fontSize: MEDIUM_FONT}}
			renderItem={({org}) => (
				<TouchableOpacity
					style={{
						marginTop: 4, borderBottomColor: '#B7BABA',
						borderBottomWidth: 1,
						paddingBottom: 2
					}}
					onPress={() => this.setState({orgName: org}, () => {
						console.log("final value:	" + this.state.orgName);
					})}>
					<Text style={styles.itemText}>{org}</Text>
				</TouchableOpacity>
			)}
			keyExtractor={org => org.toString()}
		/>
    }

SS on iOS

![Screenshot 2019-07-04 at 6 17 47 PM](https://user-images.githubusercontent.com/15075150/60667831-1a919480-9e88-11e9-861a-84cfdf8d286f.png)

SS on Android (as expected)

![Screenshot_20190704-182038~2](https://user-images.githubusercontent.com/15075150/60668263-2c276c00-9e89-11e9-80b8-66a98111c275.png)

**Comment by braianj** [comment]
which was the solution?

**Comment by neilharia7** [comment]
The `{org}` in the Text was actually a dictionary so just had to extract the values from the same inorder for it to be visible i.e. `<Text style={styles.itemText}>{org.name}</Text>`
