### ISSUE TITLE
renderSeparator doesn't exist on FlatList

### ISSUE THREAD

**Issue by floriancargoet** [mrlaessig/react-native-autocomplete-input#134]
I found that `renderSeparator` cannot work since it doesn't exist on `FlatList`. It was a prop on `ListView` and it probably stopped working since #65 

Workaround: 
```
flatListProps={{
  ItemSeparatorComponent: Separator,
}}
```

**Comment by ysrarff** [comment]
Thanks @floriancargoet, 

Saved me hours of finding out why it doesn't work.
In my case, I just needed to add some minor spacing, so I just do it like so:

`flatListProps={{
                                ItemSeparatorComponent: () => <View style={{ marginTop: 10 }} />
                            }}`
