### ISSUE TITLE
Does this library work for RN 0.60.3?

### ISSUE THREAD

**Issue by rawadrifai** [mrlaessig/react-native-autocomplete-input#136]
Hi - I copy pasted the iOS example and the result is below. Am I doing something wrong or this library is not compatible with 0.60.3 yet?

![image](https://user-images.githubusercontent.com/24530625/61501703-526b0280-a985-11e9-91d9-fe5623592d3d.png)

**Comment by DY205** [comment]
same issue ??

**Comment by n13** [comment]
Seems to have broken in 0.60.x

**Comment by n13** [comment]
Actually it works but there was an API change a while ago, so when updating the package you need to do this

```
//Before
renderItem: (item) => React.Node
//Now
renderItem: ({item, index}) => React.Node
renderItem={(item) => (
      <TouchableOpacity onPress={() => this.setState({ query: item })}>
        <Text>{item}</Text>
      </TouchableOpacity>
    )}
to:

renderItem={({ item, i }) => (
      <TouchableOpacity onPress={() => this.setState({ query: item })}>
        <Text>{item}</Text>
      </TouchableOpacity>
    )}

```

It's in the release notes, see here: https://github.com/mrlaessig/react-native-autocomplete-input/releases/tag/v4.0.0
