### ISSUE TITLE
tap outside and hide autocomplete

### ISSUE THREAD

**Issue by phonegap20** [mrlaessig/react-native-autocomplete-input#137]
Please suggest option to hide autocomplete if user taps anywhere on the screen.

Like if user taps outside below dropdown hides it's content.

https://github.com/sohobloo/react-native-modal-dropdown

**Comment by ASchwad** [comment]
I would like to have the same result as you do.

There is the option to set the property "hideResults" = true. We couldand only set it to false, when AutoComplete is focused. But i cannot get that to work with the following approach (simplified)

`state={
        hideList = true
}`

`<AutoComplete
      hideResults={this.state.hideResults}
      onFocus={() => this.setState({ hideList: false })}
/>`

**Comment by msabree** [comment]
constructor(props){
        super(props);
        this.state = {
            hideAutoComplete: false,
        }
    }


                     hideResults={this.state.hideAutoComplete}
                        onBlur={() => {
                            this.setState({
                                hideAutoComplete: true,
                            })
                        }}
                        onFocus={() => {
                            this.setState({
                                hideAutoComplete: false,
                            })
                        }}

**Comment by stzaske** [comment]
I cannot get this to work either and I'm using the same code @msabree suggested. No matter what I try hideResults never seems to change from false or whatever I originally set it to.

**Comment by Hashir524** [comment]
There's an issue with the solution. When i click results onBlur event fires. and the on Click listener on the search item is not working.

**Comment by JSJerome** [comment]
Has anyone been able to figure this out? I'm having the same issue as @Hashir524

**Comment by cschultz1272** [comment]
If anyone still needs this I've got it working for my needs which is to hide the options if the user selects an option or clicks on the next form input. If you want to dismiss when anything else is touched you could use this combined with wrapping your screen in a TouchableWithoutFeedback.
```
const [hideResults, setHideResults] = useState(true);

// hides the menu if the user selects an option
const setTextAndHideResults = item => {
    setTextInput(item);
    setHideResults(true);
  };

return (
     <Autocomplete
        data={['Option 1', 'Option 2']}
        placeholder={'Placeholder text'}
        onChangeText={text => setTextInput(text)}
        onFocus={() => setHideResults(false)}    //sets hideResults to false
        onEndEditing={() => setHideResults(true)}    //sets hideResults back to true
        defaultValue={textInput}
        hideResults={hideResults}
        renderItem={({item, i}) => (
          <TouchableOpacity onPress={() => setTextAndHideResults(item)}>
            <Text style={styles.listTextStyle}>{item}</Text>
          </TouchableOpacity>
        )}
    />
);
```
1.

**Comment by GurjantSinghAffle** [comment]
please add this code, its working fine, please have a look.
    
                                               this.state={
                                                hideResultProduct: false
                                               }
                                               onBlur={() => this.setState({ hideResultProduct: true })}
                                                onFocus={() => this.setState({ hideResultProduct: false })}
                                                hideResults={this.state.hideResultProduct}
