### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

### ISSUE THREAD

**Issue by SnehalAgrawal** [mrlaessig/react-native-autocomplete-input#138]
Hello,
Getting this warning in React Native > 0.60
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: Autocomplete

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
console.warn @ YellowBox.js:71
YellowBox.js:71 VirtualizedList: missing keys for items, make sure to specify a key or id property on each item or provide a custom keyExtractor.

**Comment by mrlaessig** [comment]
This should be fixed with `v4.2.0-rc.1`. Try to install `react-native-autocomplete-input@next`.
