### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by pixsolution** [mrlaessig/react-native-autocomplete-input#139]
Hello,

I am using your package. I am working with two api one that autocomplete and the other performs a search set the fields if the result is successful. And I am not getting the result. The code is the following:
`
```javascript
     this.state = {
      dataE: [],
      email: '',
    };
  }

  componentDidMount() {
    fetch(`${API}/dataE/`)
      .then(res => res.json())
      .then(json => {
        const { results: dataE } = json;
        this.setState({ dataE });
      });
  }

  findFdata(email) {
    if (email === '') {
      return [];
    }
    const { dataE } = this.state;
    const regex = new RegExp(`${email.trim()}`, 'i');
    return dataE.filter(Fdata => Fdata.title.search(regex) >= 0);
  }
```
```javascript
<Autocomplete style={baseStyles.autocomplete}
          autoCapitalize="none"
          autoCorrect={false}
          containerStyle={baseStyles.autocompleteContainer}
          data={dataE.length === 1 && comp(email, dataE[0].dateE) ? [] : email}
          defaultValue={email}
          onChangeText={text => this.setState({ email: text })}
          placeholder="  Email"
          renderItem={({ dateE, release_date }) => (
            <TouchableOpacity onPress={() => this.setState({ email: dateE })}>
              <Text>
                {dateE} ({release_date})
                     </Text>
            </TouchableOpacity>
          )}
        />
        <View>
          {dataE.length > 0 ? (
            <Text>{this.state.email}</Text>
          ) : (
              <Text></Text>
            )}
        </View>
```
`

I tell you how I am passing the state because both api should receive the email I write. What I get as a result in autocomplete is this
![1](https://user-images.githubusercontent.com/47191848/63211133-8b68d500-c0f3-11e9-94ba-c25477983165.png)

the api performs the search by simply writing a letter of the email she makes the suggestion.
![2](https://user-images.githubusercontent.com/47191848/63211344-2367be00-c0f6-11e9-8330-c946e14f62c1.png)

while in the otherone:
fetchDataEmail = async () => { const response = await fetch( '[https://www.mydomain.com/api/buscaruser?email=${this.setState.email}\`](https://www.mydomain.com/api/buscaruser?email=%24%7Bthis.setState.email%7D%60) );

`
```
const email = await response.json();
this.setState({ data2: email });
 Nombre.setText(nombre);
 Apellido.setText(apellido);
 Telefono.setText(telefono);
````
`
```
<MaterialCommunityIcons
              name="magnify"
              size={43}
              color="black"
              onPress={() => {
                email: this.state.email
              }}
            />
````
![3](https://user-images.githubusercontent.com/47191848/63211347-295d9f00-c0f6-11e9-98b0-9d5fde30100b.png)

Hope you can help

Regards

**Comment by sandipjc** [comment]
> Hello,
> 
> I am using your package. I am working with two api one that autocomplete and the other performs a search set the fields if the result is successful. And I am not getting the result. The code is the following:
> `
> 
> ```js
>      this.state = {
>       dataE: [],
>       email: '',
>     };
>   }
> 
>   componentDidMount() {
>     fetch(`${API}/dataE/`)
>       .then(res => res.json())
>       .then(json => {
>         const { results: dataE } = json;
>         this.setState({ dataE });
>       });
>   }
> 
>   findFdata(email) {
>     if (email === '') {
>       return [];
>     }
>     const { dataE } = this.state;
>     const regex = new RegExp(`${email.trim()}`, 'i');
>     return dataE.filter(Fdata => Fdata.title.search(regex) >= 0);
>   }
> ```
> 
> ```js
> <Autocomplete style={baseStyles.autocomplete}
>           autoCapitalize="none"
>           autoCorrect={false}
>           containerStyle={baseStyles.autocompleteContainer}
>           data={dataE.length === 1 && comp(email, dataE[0].dateE) ? [] : email}
>           defaultValue={email}
>           onChangeText={text => this.setState({ email: text })}
>           placeholder="  Email"
>           renderItem={({ dateE, release_date }) => (
>             <TouchableOpacity onPress={() => this.setState({ email: dateE })}>
>               <Text>
>                 {dateE} ({release_date})
>                      </Text>
>             </TouchableOpacity>
>           )}
>         />
>         <View>
>           {dataE.length > 0 ? (
>             <Text>{this.state.email}</Text>
>           ) : (
>               <Text></Text>
>             )}
>         </View>
> ```
> 
> `
> 
> I tell you how I am passing the state because both api should receive the email I write. What I get as a result in autocomplete is this
> ![1](https://user-images.githubusercontent.com/47191848/63211133-8b68d500-c0f3-11e9-94ba-c25477983165.png)
> 
> the api performs the search by simply writing a letter of the email she makes the suggestion.
> ![2](https://user-images.githubusercontent.com/47191848/63211344-2367be00-c0f6-11e9-8330-c946e14f62c1.png)
> 
> while in the otherone:
> fetchDataEmail = async () => { const response = await fetch( '[https://www.mydomain.com/api/buscaruser?email=${this.setState.email}`](https://www.mydomain.com/api/buscaruser?email=%24%7Bthis.setState.email%7D%60) );
> 
> `
> 
> ```
> const email = await response.json();
> this.setState({ data2: email });
>  Nombre.setText(nombre);
>  Apellido.setText(apellido);
>  Telefono.setText(telefono);
> ```
> 
> `
> 
> ```
> <MaterialCommunityIcons
>               name="magnify"
>               size={43}
>               color="black"
>               onPress={() => {
>                 email: this.state.email
>               }}
>             />
> ```
> 
> ![3](https://user-images.githubusercontent.com/47191848/63211347-295d9f00-c0f6-11e9-98b0-9d5fde30100b.png)
> 
> Hope you can help
> 
> Regards

Hi
I resolve this issue by installing 'native-base-autocomplete'.

Uninstall 'react-native-autocomplete-input' and install 'native-base-autocomplete'.
Link: https://www.npmjs.com/package/native-base-autocomplete

Replace below import link, with old one.
import Autocomplete from 'native-base-autocomplete';

Other code keep same and check.

**Comment by djpetenice** [comment]
This is my current renderItem:

renderItem={({ station,code}) => (

How do I change to the new method as I'm getting the blank results?
