### ISSUE TITLE
autocomplete list not scrolling inside parent ScrollView

### ISSUE THREAD

**Issue by zuhairnaqi** [mrlaessig/react-native-autocomplete-input#149]
I have a form. All fields are used in ScrollView to scroll form. All are working fine but the autocomplete list isnot scrolling because of parent ScrollView when i remove ScrollView from parent then i works.

**Comment by valentyna-refundit** [comment]
faced with the same problem, someone found a solution?

**Comment by lovetofail** [comment]
On Android nestedScrollEnabled={true} should be added to the inner Flatlist.
So try <Autocomplete nestedScrollEnabled={true}

**Comment by zuhairnaqi** [comment]
> On Android nestedScrollEnabled={true} should be added to the inner Flatlist.
> So try <Autocomplete nestedScrollEnabled={true}

Not works :(

**Comment by dquessenberry** [comment]
Hey @zuhairnaqi, @lovetofail is on the right track, but the nestedScrollEnabled={true} prop doesn't appear to be passed on to the inner ScrollView component. Try utilizing the Autocomplete component's flatListProps prop instead. This works for me:

`
<Autocomplete
    flatListProps={{
        nestedScrollEnabled: true,
    }}
    ...
/>
`

**Comment by tayloraleach** [comment]
Did this work for you? It seems to have no effect on my list of items. I am passing a custom <View> to the item render but they do not scroll when I set a fixed height to the listStyles.

**Comment by lovetofail** [comment]
I patch this file - "myproject"\node_modules\react-native-dropdown-autocomplete\components\Dropdown\index.js 
Adding "nestedScrollEnabled" to enable it.
```
              ListFooterComponent={this.renderFooter} //row 515
              ListHeaderComponent={this.renderHeader} //row 516
              nestedScrollEnabled //<-- adding this line //row 517
```

**Comment by tayloraleach** [comment]
> I patch this file - "myproject"\node_modules\react-native-dropdown-autocomplete\components\Dropdown\index.js
> Adding "nestedScrollEnabled" to enable it.
> 
> ```
>               ListFooterComponent={this.renderFooter} //row 515
>               ListHeaderComponent={this.renderHeader} //row 516
>               nestedScrollEnabled //<-- adding this line //row 517
> ```

Am I confused or is that file not in this repo? I have `/myProject/node_modules/react-native-autocomplete-input/index.js`

**Comment by lovetofail** [comment]
Yes, sorry. I was talking about this project - react-native-dropdown-autocomplete
But it may be applicable to this project too.

**Comment by tayloraleach** [comment]
Ah. The flatlist props seem to work anyways. My list does scroll but it is in an absolute positioned parent and it won't scroll when the elements go beyond the parent and overlay the elements below.
