### ISSUE TITLE
AutoComplete dropdown in ios is not scrollable

### ISSUE THREAD

**Issue by barak109** [mrlaessig/react-native-autocomplete-input#151]
I can't scroll my drop down list in ios but in android i can.
I checked a lot of suggestions and nothing doesn't help.

this is my code 
`return (
      <View style={styles.container}>
        {showAddChar && (
          <Text style={styles.addChar} onPress={this.onChoosenItem}>
            +
          </Text>
        )}
        <Autocomplete
          data={data}
          defaultValue={query}
          onChangeText={(text: string) =>
            this.setState({ query: text, hideResult: false })
          }
          keyExtractor={index => index['id'].toString()}
          inputContainerStyle={styles.inputContainerStyle}
          listContainerStyle={{}}
          listStyle={styles.listStyle}
          style={{ fontSize: 18 }}
          hideResults={hideResult}
          placeholder={placeholder}
          renderItem={({ item }) => (
            <TouchableOpacity
              style={styles.item}
              onPress={() => this.onChoosenItem(item)}
            >
              <Text>{item['name']}</Text>
            </TouchableOpacity>
          )}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0
  },
  addChar: {
    zIndex: 1,
    position: 'absolute',
    fontSize: 30,
    right: 0,
    top: 0
  },
  inputContainerStyle: {
    borderColor: 'rgb(70, 48, 235)',
    borderBottomWidth: 3,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0
  },
  //   listContainerStyle: {height:filteredMembers.length * 70},
  listStyle: {
    borderColor: 'grey',
    margin: 0,
    overflow: 'scroll',
    maxHeight: 200
  },
  item: {
    fontSize: 16,
    borderBottomColor: 'grey',
    borderBottomWidth: 2,
    padding: 12
  }
});`

***** that what i get in IOS
![Screen Shot 2019-10-29 at 12 12 48](https://user-images.githubusercontent.com/50053032/67757974-7ab6d280-fa45-11e9-8592-9b73c99d729b.png)

**Comment by sensoft2207** [comment]
Same issue in IOS. Any Solution?

**Comment by Bashamd455** [comment]
Hi, @barak109  I am also facing the same issue in iOS and Android. Did you find any solution?

**Comment by tayloraleach** [comment]
I can scroll my dropdown in iOS but not Android. I have another similar issue open as well. Wondering if most people who use this package only have small data sets that do not need scroll? This is a major issue IMO and will be a deal-breaker for me :(

**Comment by Bashamd455** [comment]
Hey, @tayloraleach I could fix the scrolling issue in Android and iOS by following the https://github.com/mrlaessig/react-native-autocomplete-input/issues/64#issuecomment-507388606 and by sending **listStyle={{ maxHeight: 350 }}** prop to AutoComplete Input.

**Comment by Garamani** [comment]
The solutions suggested here didn't work for me, the solution that worked:

adding `flex: 1` to listContainerStyle which is the parent of FlatList.

**Comment by soccermind** [comment]
> The solutions suggested here didn't work for me, the solution that worked:
> 
> * adding `flex: 1` to listContainerStyle which is the parent of FlatList.
> * adding style: {height: 400} to flatListProps

After trying all other options, this is the only one that worked for me on both iOS and android, thank you so much for sharing!
