### ISSUE TITLE
I am using react-native": "0.60.5" and I am getting the warning. componentWillReceiveProps is deprecated and will be removed in the next major verison. I want to ask, would it be updated in future so that I could continue using this library.

### ISSUE THREAD

**Issue by IbrahimSheikh24** [mrlaessig/react-native-autocomplete-input#152]
Can I get the confirmation on this issue to continue using this library without getting any problem in next version of react native.

**Comment by mrlaessig** [comment]
Related to #138.

**Comment by IbrahimSheikh24** [comment]
@mrlaessig 
Now I am using "react-native-autocomplete-input": "^4.2.0-rc.1".
But still I am getting same warning.
![Screenshot_20191106-130759](https://user-images.githubusercontent.com/57092389/68278159-c77a5900-0096-11ea-9b9a-1e4aa6a97b96.jpg)

![picturemessage_mlb4o1fu u2f](https://user-images.githubusercontent.com/57092389/68278353-1de79780-0097-11ea-91c1-d6e81cdfffeb.png)

I have attached screenshots.

**Comment by mrlaessig** [comment]
Try to install `4.2.0-rc.2` this should definitely not use `componentWillReceiveProps` aymore.
