### ISSUE TITLE
setState() in onShowResults does not work???

### ISSUE THREAD

**Issue by RohitHegde44** [mrlaessig/react-native-autocomplete-input#153]
I land a Maximum update depth reached error on applying setState inside this function

**Comment by mrlaessig** [comment]
Did you try to used `4.2.0-rc.2`. It's not using state internally anymore.

**Comment by RohitHegde44** [comment]
The latest one?

**Comment by mrlaessig** [comment]
`npm i react-native-autocomplete-input@4.2.0-rc.2`

**Comment by RohitHegde44** [comment]
Tried that doesn't work

**Comment by mrlaessig** [comment]
Without the code it's hard to tell anything. Looks like calling `setState()` in `onShowResults` is causing a infinity loop.

**Comment by RohitHegde44** [comment]
Yup

<AutoComplete
						style={{backgroundColor:colours.navBarColor,color:colours.white,fontFamily:fontsTata.UReg}}
						containerStyle={{flex:1,position:'absolute',zIndex:1,top:-0.5,bottom:-5,left:-1,right:-1}}
						listContainerStyle={{width:WIDTH,paddingHorizontal:10}}
						inputContainerStyle={{paddingHorizontal:10,}}
						data={searchedData.length === 1 && comp(query,searchedData[0]) ? [] : searchedData }
						onChangeText={text => this.setState({query : text})}
						placeholder='Search by Vehicle Id'
						placeholderTextColor={colours.white}
						defaultValue={this.state.query}
						clearButtonMode='always'
						clearTextOnFocus={true}
						onShowResults={(type)=>{
							// console.warn('TYPE',type)
							// this.setState({ absoluteB: type ? 10 : HEIGHT*0.7 })
							absoluteB = type ? 0 : HEIGHT*0.62
						}}
						renderItem={({item,index}) => {
							// console.warn('Dfilm',item)
							return(
								<TouchableOpacity
									key={index}
									activeOpacity={0.5}
									style={{padding:10,backgroundColor:colours.navBarColor,width:'100%'}}
									onPress={()=>this.setState({query: item},()=>this.animateToRegion(item))}
								>
									<Text style={{color:colours.white,fontFamily:fontsTata.UReg}}>{item}</Text>
								</TouchableOpacity>
							)
						}}
					/>



I believe the setstate in onchangeText is causing this

**Comment by mrlaessig** [comment]
Yes, looks like this is causing a loop. You can already check if the data you pass in has length greater 0  in the parent component and set what ever you like.

```
const absoluteB = data.length > 0 ? 10 : HEIGHT0.62
```
