### ISSUE TITLE
Style of Auto Complete Text Box not working

### ISSUE THREAD

**Issue by sagarrs** [mrlaessig/react-native-autocomplete-input#154]
hi, everyone, the style is not working . I tried modifying both "inputContainerStyle" and "containerStyle".

i wanted a textbox style with just ” borderBottomWidth: 1 “, can you please let me know how to modify the “Autocomplete” textBox style.

Thanks,

**Comment by LuisGarcia19** [comment]
Hi, Autocomplete use a TextInput and that styles are not supported.

More info here:
https://facebook.github.io/react-native/docs/textinput#style
