### ISSUE TITLE
Background Colour and click issue in ios 

### ISSUE THREAD

**Issue by bhargav6744** [mrlaessig/react-native-autocomplete-input#155]
![image](https://user-images.githubusercontent.com/19975255/71280884-7a222480-2382-11ea-85cd-02c926ddf9e2.png)

**Comment by dinhbathi2702** [comment]
@bhargav6744 i also have this issue . And i fixed it by set zIndex on View Parent 
Example :
`<View style={{zIndex:1}}>
<View style={{zIndex:1}}>
<Autocomplete/>

<View>
 <Image
                source={Images.Shape}
                resizeMode="contain"
               
              />
<View>`
