### ISSUE TITLE
borders style

### ISSUE THREAD

**Issue by CharlotteRdn** [mrlaessig/react-native-autocomplete-input#160]
Hi, 

I'm trying to delete the top, right and left borders of my textInput (so obviously, I'd like to have just the bottom border :) )
I tried borderTop : 0 / and  'transparent' but it's not working 
borderStyle didn't work either 

I get this: 
https://zupimages.net/viewer.php?id=20/03/6c88.bmp

my code is this: 

  ```
<Autocomplete
              style={styles.inputContainer}
              autoCapitalize="none"
              autoCorrect={false}
              data={this.findAirports(query_arrival)}
              defaultValue={this.findAirports(query_start)}
              onChangeText={text => this.setState({ query_start: text })}
              placeholder="Enter Start airports"
              renderItem={({ airport }) => (
                <TouchableOpacity
                  onPress={() => this.setState({ query_start: airport })}
                >
                  <Text style={styles.h2}>{airport}-</Text>
                </TouchableOpacity>
              )}
            />
          </View>
          <View style={styles.container}>
            <Autocomplete
            style={styles.inputContainer}
              autoCapitalize="none"
              autoCorrect={false}
              data={this.findAirports(query_arrival)}
              defaultValue={this.findAirports(query_arrival)}
              onChangeText={text => this.setState({ query_arrival: text })}
              placeholder="Enter Arrival airports"
              renderItem={({ airport }) => (
                <TouchableOpacity
                  onPress={() => this.setState({ query_arrival: airport })}
                >
                  <Text style={styles.h2}>{airport}-</Text>
                </TouchableOpacity>
              )}
            />

with this style: 
```
inputContainer: {
borderStyle: 'dashed',
minWidth: 300,
width: "90%",
height: 55,
backgroundColor: "transparent",
padding: 5,
color: "#6C6363",
fontSize: 18,
fontFamily: "Roboto",
borderBottomWidth: 1,
borderBottomColor: "rgba(108, 99, 99, .7)"
},
```
If I can get any help that's really nice, thanks for reading and for any help !

**Comment by CharlotteRdn** [comment]
I removed padding and borderStyle, but still the same problem...

**Comment by WeeCoopTech** [comment]
It seems that's it's impossible with that package.

I could do what I wanted to do with 'native base autocomplete' . So, it doesn't completely answer the question but it allows to do the right thing !

Maybe this will help someone !

**Comment by KiranC10** [comment]
you need to set the borderWidth to 0

inputContainerStyle={{ borderWidth: 0, borderBottomWidth: 1 }}

**Comment by WeeCoopTech** [comment]
Thanks for the answer !
