### ISSUE TITLE
How do I display the complete list items with focus on the input?

### ISSUE THREAD

**Issue by behi1989** [mrlaessig/react-native-autocomplete-input#161]
I want to be display the list items by typing a letter and also displayed the complete list items by focus on the input too.
How can I do this?

**Comment by behi1989** [comment]
Now, just typing a letter in the list is displayed.

**Comment by KiranC10** [comment]
I think your concern is about this
 **hideResults={query.length < 3 ? true : false}**
you can change the length to get your result

**Comment by behi1989** [comment]
> I think your concern is about this
> **hideResults={query.length < 3 ? true : false}**
> you can change the length to get your result

thank you,
But I mean to open the list with focus on input without typing.

**Comment by behi1989** [comment]
I used:
ref={el => this._dropdown_3 = el}
and call this._dropdown_3.show() in button

**Comment by Chugunenok** [comment]
I use the following solution

`<Autocomplete
hideResults={this.state.hideResults}
onFocus={() => this.setState({ hideResults: false })}
renderItem={({ item, i }) => (
  <TouchableOpacity onPress={() => this.setState({ hideResults: true })}>
    <Text>{item.name}</Text>
  </TouchableOpacity>
)}
/>`

**Comment by trugdn** [comment]
working for me:
hideResults={isHideResultsAutocomplete}
onFocus={() => setHideResultsAutocomplete(false)}
onEndEditing={() => setHideResultsAutocomplete(true)}

**Comment by behi1989** [comment]
> 
> 
> working for me:
> hideResults={isHideResultsAutocomplete}
> onFocus={() => setHideResultsAutocomplete(false)}
> onEndEditing={() => setHideResultsAutocomplete(true)}

Yes,
I used the same
Anyway, thank you

**Comment by yangfreezy** [comment]
The issue with this approach is that if you select an item, but then delete it and try typing again, the results does not show. I've tried adding "onEditing={() => setHideResults(false)}" but that hasn't solved that edgecase for me. Anyone else encounter this issue?
