### ISSUE TITLE
Result data not showing

### ISSUE THREAD

**Issue by karimkun** [mrlaessig/react-native-autocomplete-input#162]
Hi,

When using the autocomplete in my app, I can't see the suggestion text in search result, its only showing empty array while searching, I think it's not binding the text of the result. 
Have you any solution please, I'm stuck with it.

Thanks in advance.
Karim

**Comment by Sharkanana** [comment]
You need to provide more information for anyone to be able to give you any sort of suggestion.  Perhaps click through to the more specific android/ios examples from the readme.

**Comment by bilalyaqoob** [comment]
result list below input is always open but it opens the list and black

**Comment by bilalyaqoob** [comment]
{"index": 1, "item": {"_id": "QSVFeqge2j5nJH6j", "handle": "SIDEORDERS", "image_url": "https://secure.vendhq.com/images/placeholder/product/no-image-white-standard.png", "name": "SIDE ORDERS", "type": "SIDE ORDERS", "variants": [[Object], [Object], [Object], [Object], [Object], [Object]]}, "separators": {"highlight": [Function highlight], "unhighlight": [Function unhighlight], "updateProps": [Function updateProps]}}  brother this is the result in renderitem you have to get data from item

**Comment by bilalyaqoob** [comment]
now i am getting the data the example is wrong

**Comment by bilalyaqoob** [comment]
should i submit the pr for this

**Comment by bilalyaqoob** [comment]
https://github.com/mrlaessig/react-native-autocomplete-input/pull/190
