### ISSUE TITLE
Two new warnings with latest verison

### ISSUE THREAD

**Issue by Durgaa-G** [mrlaessig/react-native-autocomplete-input#168]
- VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

- componentWillReceiveProps has been deprecated

**Comment by montusokar** [comment]
same here, is in there a way to remove the warnings from the component call?

**Comment by mrlaessig** [comment]
Have you tired to install `npm i react-native-autocomplete-input@next`?

**Comment by Durgaa-G** [comment]
No @mrlaessig , I installed with npm i react-native-autocomplete-input as mentioned in doc

**Comment by tayloraleach** [comment]
Any word on updating this?
I quickly looked in the code and could not locate the `componentWillReceiveProps` lifecycle method? Where is it being called?

**Comment by Durgaa-G** [comment]
Hi,
Its not showing here on Guthub, But the version(4.1.0) we installed using npm is showing this error. There it is avilable in index.js line 104.  Below is error message 


Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Autocomplete

**Comment by mrlaessig** [comment]
Released a new version without using the lifecycle methods
