### ISSUE TITLE
How to get rid of the border of autoComplete?

### ISSUE THREAD

**Issue by changyu2hao** [mrlaessig/react-native-autocomplete-input#170]
I'm trying to get rid of the border. I set borderwidth:0, at the autocompleteContainer, but it doesn't work

**Comment by HackedBeat** [comment]
@changyu2hao 
You need to use `inputContainerStyle` prop:

```
  inputContainerStyle={{ borderWidth: 0 }}
```

**Comment by the-smart-home-maker** [comment]
@HackedBeat has the answer that solves the issue. Guess one could close the issue...
