### ISSUE TITLE
The results of the first Autocomplete float behind the second Autocomplete field

### ISSUE THREAD

**Issue by eliataylor** [mrlaessig/react-native-autocomplete-input#172]
If you have two or more vertically stacked components, the results float behind those below (as well as my Picker components). `zIndex` does not seem to help

```
renderItem({item, i, separators}) {
        return (
            <TouchableOpacity style={styles.acResult} key={i} onPress={() => this.onSelect(item)}>
                <Text style={styles.acResultText}>
                    {item.label}
                </Text>
            </TouchableOpacity>
        )
    }

<View style={styles.autocompleteContainer}>
                    <Autocomplete
                        autoCapitalize="none"
                        autoCorrect={false}
                        keyExtractor={item => item.id}
                        data={this.findResult(this.state.query)}
                        placeholder={this.props.field.label}
                        defaultValue={this.state.query}
                        onChangeText={text => this.setState({query: text})}
                        renderItem={this.renderItem}
                    />
                </View>
```

![Screen Shot 2020-06-29 at 10 22 35 AM](https://user-images.githubusercontent.com/6335974/86036427-b352e580-b9f2-11ea-90dd-9d4df99ff4cc.png)

My styles are:

```
acResult: {
        zIndex:99999,
        backgroundColor:Colors.snow,
    },
    acResultText: {
        paddingVertical:5,
        paddingLeft:5,
        fontSize: 18,
        backgroundColor:Colors.snow,
        color:Colors.charcoal
    },
    autocompleteContainer: {
        backgroundColor:Colors.snow,
        flex: 1,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
        zIndex: 1
    }
```

**Comment by acoulon99** [comment]
@eliataylor 
The base Autocomplete containerStyle includes a `zIndex` of 1, so I bet it'll work if you also set its `zIndex`.

https://github.com/mrlaessig/react-native-autocomplete-input/blob/537be1858d38dc94642849bfa411e9677a45a534/index.js#L239
https://github.com/mrlaessig/react-native-autocomplete-input/blob/537be1858d38dc94642849bfa411e9677a45a534/index.js#L197

**Comment by ahtisham09** [comment]
> If you have two or more vertically stacked components, the results float behind those below (as well as my Picker components). `zIndex` does not seem to help
> 
> ```
> renderItem({item, i, separators}) {
>         return (
>             <TouchableOpacity style={styles.acResult} key={i} onPress={() => this.onSelect(item)}>
>                 <Text style={styles.acResultText}>
>                     {item.label}
>                 </Text>
>             </TouchableOpacity>
>         )
>     }
> 
> <View style={styles.autocompleteContainer}>
>                     <Autocomplete
>                         autoCapitalize="none"
>                         autoCorrect={false}
>                         keyExtractor={item => item.id}
>                         data={this.findResult(this.state.query)}
>                         placeholder={this.props.field.label}
>                         defaultValue={this.state.query}
>                         onChangeText={text => this.setState({query: text})}
>                         renderItem={this.renderItem}
>                     />
>                 </View>
> ```
> 
> ![Screen Shot 2020-06-29 at 10 22 35 AM](https://user-images.githubusercontent.com/6335974/86036427-b352e580-b9f2-11ea-90dd-9d4df99ff4cc.png)
> 
> My styles are:
> 
> ```
> acResult: {
>         zIndex:99999,
>         backgroundColor:Colors.snow,
>     },
>     acResultText: {
>         paddingVertical:5,
>         paddingLeft:5,
>         fontSize: 18,
>         backgroundColor:Colors.snow,
>         color:Colors.charcoal
>     },
>     autocompleteContainer: {
>         backgroundColor:Colors.snow,
>         flex: 1,
>         left: 0,
>         position: 'absolute',
>         right: 0,
>         top: 0,
>         zIndex: 1
>     }
> ```

Did you get the solution of this problem i am also facing this problem

**Comment by eliataylor** [comment]
@ahtisham09, i did not but got a comparable solution working with `react-native-picker-modal-view`

(also consider it's not really necessary to quote the entire Issue)

**Comment by paritosh-yadav** [comment]
Any update on this...facing similar issue.

**Comment by iamsrikanthnani** [comment]
@paritosh-yadav simply set the **zIndex:-10** to the below component(second autocomplete).

**Comment by ahtisham09** [comment]
@paritosh-yadav i solve this issue with any styling like ZIndex Simply just create a view without any styling 
<View mainContainer>
<AutoComplete/>
<View>
<AutoComplete/>
<View>
<AutoComplete/>
<View ( if you want to add button any other component add in this view/>
</View>
</View>
</View>

I hope this snippet will help you for solving this problem
