### ISSUE TITLE
Components below AutoComplete shifting downwards in android. 

### ISSUE THREAD

**Issue by MehmoodArib** [mrlaessig/react-native-autocomplete-input#173]
![Simulator Screen Shot - iPhone 11 - 2020-07-14 at 16 51 14](https://user-images.githubusercontent.com/32247358/87420086-447cab80-c5f2-11ea-9a29-84a85df51c60.png)
![Screenshot_1594725664](https://user-images.githubusercontent.com/32247358/87420094-47779c00-c5f2-11ea-8238-7a6015208072.png)

**Comment by vaibhavgadekar** [comment]
Have you get answer??

**Comment by mrlaessig** [comment]
Did you check the [note on Android](https://github.com/mrlaessig/react-native-autocomplete-input#android) in the readme? Feel free to reopen if the issue persists.
