### ISSUE TITLE
border style

### ISSUE THREAD

**Issue by helenapaixao** [mrlaessig/react-native-autocomplete-input#177]
Hi,
I want to leave my autocomplete as in the image, how could I do?

https://zupimages.net/viewer.php?id=20/35/sl1e.png

thanks

**Comment by e1016** [comment]
No way to do it via props.

Edit this file`<project>/node_modules/react-native-autocomplete-input/index.js`

find...

```javascript
const border = {
  borderColor: '#b9b9b9',
  borderRadius: 1,
  borderWidth: 1
};
```

and comment.

**Comment by helenapaixao** [comment]
thanks @e1016
