### ISSUE TITLE
selected value not shown 

### ISSUE THREAD

**Issue by nyaupanegopal** [mrlaessig/react-native-autocomplete-input#180]
while using functional component, selected value not shown in autocomplete input but it shows selected result while pushing to  another text input

**Comment by nurycaroline** [comment]
I have the same problem, you solved?

**Comment by sachinxagrawal** [comment]
use font color for text.. style={{color:'#000000'}}

**Comment by mrlaessig** [comment]
With the [latest release](https://github.com/mrlaessig/react-native-autocomplete-input/releases/tag/v5.0.0) it should work work with functional components as well. Checkout the [example snack](https://byteburgers.com/autocomplete). Feel free to reopen if the issue persists.
