### ISSUE TITLE
Cannot read property 'style' of undefined with React Native version "0.63.2"

### ISSUE THREAD

**Issue by simabui** [mrlaessig/react-native-autocomplete-input#193]
I am receiving  error **Cannot read property 'style' of undefined** in my app during importing
https://snack.expo.io/@havm/react-native-autocomplete-input

**Comment by simabui** [comment]
as workaround it works on React Native version 0.62.2

**Comment by rajprajapat7** [comment]
Getting error 
TypeError: Cannot read property 'style' of undefined
node_modules\react-native-autocomplete-input\index.js

react-native:0.63.4
"react-native-autocomplete-input": "^4.2.0"

**Comment by mrlaessig** [comment]
This should be fixed with the [5.0.0-beta.0](https://www.npmjs.com/package/react-native-autocomplete-input/v/5.0.0-beta.0) release
