### ISSUE TITLE
Android autocomplete input height remains same 

### ISSUE THREAD

**Issue by komal-rana-RN** [mrlaessig/react-native-autocomplete-input#194]
![Screenshot_1614087829](https://user-images.githubusercontent.com/75668681/108852213-518f5d80-760b-11eb-8d7b-b459e25daa39.png)

**Comment by mrlaessig** [comment]
Did wrap the component into an absolute positioned container on Android?

**Comment by mrlaessig** [comment]
I will close the issue for now. Feel free to reopen if your issues persists.
