### ISSUE TITLE
Can not remove FlatList's border 

### ISSUE THREAD

**Issue by jeanyhuynh** [mrlaessig/react-native-autocomplete-input#197]
How to remove the border or add my style on result FlatList ? Hope anyone can help. Thanks

**Comment by mrlaessig** [comment]
Did you try to pass your styles down to the `<FlatList />`?

```
<Autocomplete
  // ... other props
  flatListProps={{
    style: styles.flatList,
    // ... other FlatList props
  }}
/>

```

**Comment by jeanyhuynh** [comment]
Hi @mrlaessig,
Thanks for your help. You save my life. ^^
