### ISSUE TITLE
Autocomplete inside scrollview

### ISSUE THREAD

**Issue by smervs** [mrlaessig/react-native-autocomplete-input#203]
Still got a console error using autocomplete v5 and react native 0.64

- VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

Is there any way to remove the warning? Thank you.

**Comment by jaydeepk3** [comment]
I got the same issue

**Comment by amin79** [comment]
I have also the same problem. Even with "nestedScrollEnabled" it does not work.

**Comment by avesgit** [comment]
Same problem

**Comment by nikopolidi** [comment]
no it's not fixed

**Comment by xegulon** [comment]
Yeah, I'd like to have a solution for this issue also.

**Comment by rohitshelhalkar** [comment]
same problem on ios
console.error: VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

**Comment by MarinaArimany** [comment]
Have you found a solution to this problem?
Thanks
