### ISSUE TITLE
keyboardShouldPersistTaps typo

### ISSUE THREAD

**Issue by michaeledrian** [mrlaessig/react-native-autocomplete-input#204]
Dear developer there is typo on index.js file on the keyboardShouldPersistTaps :
PropTypes.oneOf(['always', '**handeld**', 'never']),

You need to change it into:
PropTypes.oneOf(['always', '**handled**', 'never']),

**Comment by mrlaessig** [comment]
Thx for pointing out! Type has been fixed in the lates release.

**Comment by michaeledrian** [comment]
Your welcome boss!
