### ISSUE TITLE
Double Tap to Select the Item [Android]

### ISSUE THREAD

**Issue by michaeledrian** [mrlaessig/react-native-autocomplete-input#205]
Hi Developer,

When I implemented keyboardShouldPersistTaps,
I need to tap twice the item to select the item (the first tap dismiss the keyboard and the second one to select the item).
This issue only happened in Android.

**Comment by mrlaessig** [comment]
Hey @michaeledrian, check out the [example](https://byteburgers.com/autocomplete) you have to pass `keyboardShouldPersistTaps` as `flatListProps` props. 
```
flatListProps={{
  keyboardShouldPersistTaps: 'always',
  keyExtractor: (movie: Movie) => movie.id,
    renderItem: ({ item: { title } } : Movie) => (
      <TouchableOpacity onPress={() => setQuery(title)}>
        <Text style={styles.itemText}>{title}</Text>
      </TouchableOpacity>
    ),
}}
            ```
