### ISSUE TITLE
How to enable scrolling for the autocomplete flatlist items

### ISSUE THREAD

**Issue by silencer07** [mrlaessig/react-native-autocomplete-input#208]
I have an autocomplete field inside an overlay. my problem is that scrolling through the items(items overflow to the screen) does not work. I tried wrapping it inside scrollview but does not work.

How should I do this??

Edit:  in ios, you can scroll but for some reason it "rubberbands" back to the top when you stop scrolling. in android it does not complete work

**Comment by horizonlime** [comment]
I've been working through this exact problem myself! 

The listStyle prop no longer works with AutoComplete so you need to add it as a style to flatListProps. I set the listStyle to have a maxHeight of 350 and now it scrolls without bouncing back to the top of the list. 

Hope this helps!

```
<Autocomplete
         flatListProps={{
              style: styles.listStyle, // ADD MAXHEIGHT TO flatListProps HERE
              keyExtractor: ...,
              renderItem: ...
         }}
/>


const styles = StyleSheet.create({
        listStyle: {
	     maxHeight: 350
	},
})
```

**Comment by silencer07** [comment]
@horizonlime thanks for the iOS fix. 

I hope there is a workaround for the android as well.

**Comment by Garamani** [comment]
The solutions suggested here didn't work for me, the solution that worked:

adding `flex: 1` to listContainerStyle which is the parent of FlatList.
