### ISSUE TITLE
How to add defaultValue='foo' to AutocompleteInput

### ISSUE THREAD

**Issue by jake17007** [mrlaessig/react-native-autocomplete-input#210]
With a normal InputText, you can supply a value to pre-fill the input box (use can edit it after).

However, I tried this with AutocompleteInput and it doesn't work.

Is there a workaround?

**Comment by sebastien-f** [comment]
You can use the "value" prop, otherwise you probably could use the renderTextInput functions from the props and render your own textinput

**Comment by sebastien-f** [comment]
I was looking at the source code, you can even directly add defaultValue to the <Autocomplete> tag, it's transfered to the underlying textinput. I also tested it, it's working properly

**Comment by mitjnextt** [comment]
That's correct @sebastien-f , `defaultValue={'Foo'}` props can be used.
