### ISSUE TITLE
List displaying behind other components

### ISSUE THREAD

**Issue by sinclas** [mrlaessig/react-native-autocomplete-input#212]
Hi,

I have this component on a form with components directly under it.  Is there a way I can set the list to display above the other component below it?  It's currently displaying behind it.  Do I set the list container's ZIndex?

Thanks!
Steve

**Comment by deepslam** [comment]
Same issue

**Comment by mitjnextt** [comment]
Hey Guys, Wrap your <AutocompleteInput with a <View> and provide some good zIndex to your <View>, If this does not work. Try defining you list inside flatListProps={{}}
Let me know if it does not work!

**Comment by indapublic** [comment]
Same for me but I used a Android trick from manual.

```
//...

render() {
  return(
    <View>
      <View style={styles.autocompleteContainer}>
        <Autocomplete {/* your props */} />
      </View>
      <View>
        <Text>Some content</Text>
      </View>
    </View>
  );
}

//...

const styles = StyleSheet.create({
  autocompleteContainer: {
    flex: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1
  }
});
```

It means that iOS doesn't support overflows too? Probably this style should be implemented on component level?

**Comment by erdong-fe** [comment]
The problem of zIndex

**Comment by MrSiby** [comment]
Same issue with the suggestions list appearing behind any element below it. I've tried setting z-index on everything I could but the problem remains.

Any attempt to select a suggestion will pass through to the element it's overlapping.

**Comment by abhijitkumar360** [comment]
guys don't take tension . I have use listStyle={{position:'relative'}} inside Autocomplete.

**Comment by SamanthaChia** [comment]
I used listContainerStyle and simply added z-index in there if the result list ends up behind  other components! :) hope it helps

**Comment by Stophface** [comment]
Yep, this is a huge problem!

**Comment by W1nstar** [comment]
On Android, my problem seems to be the fact that the dropdown doesn't overflow the container view of the Autocomplete component. Even when absolute, it doesn't show, you can only see half the dropdown. Setting it to relative isn't a possibility in my project, so I'm still looking for a solution. zIndex does nothing, elevation doesn't seem to work on suggestionsListContainer nor any other component.

Any suggestion would be appreciated!

**Comment by cs-manughian** [comment]
> On Android, my problem seems to be the fact that the dropdown doesn't overflow the container view of the Autocomplete component. Even when absolute, it doesn't show, you can only see half the dropdown. Setting it to relative isn't a possibility in my project, so I'm still looking for a solution. zIndex does nothing, elevation doesn't seem to work on suggestionsListContainer nor any other component.
> 
> Any suggestion would be appreciated!

The solution [here ](https://github.com/mrlaessig/react-native-autocomplete-input/issues/212#issuecomment-986152087) worked for me, on both platforms, but it really depends on the styling on your parent component. Could it be interfering? I'd try it out on an empty screen to see if it works, then one by one can add your parent styles. Let me know if that helps, or possibly post a code snippet.

**Comment by Jean-Kenned** [comment]
My workaround to this problem was wrapper the components just bellow the input with a `View` with negative zIndex:`zIndex: -1`. This worked both in IOS and Android.

**Comment by ApluUalberta** [comment]
This is still a huge issue, though we can manipulate the display over other elements using `position: "absolute"` and zIndex, this could affect styling principles across an application. This needs to be fixed.

**Comment by Dsalvat596** [comment]
Still a problem.  I have to display the autocomplete input in a modal.  The listItems appear behind the modal.  Please fix.
