### ISSUE TITLE
Making border invisible

### ISSUE THREAD

**Issue by imsam67** [mrlaessig/react-native-autocomplete-input#218]
I can't seem to get rid of the border around the input box. I tried adjusting `style` both for the `<View>`  and the `AutoCompleteInput` by playing with `borderWidth` and `borderColor` to no avail.

I'm trying to make the `AutoCompleteInput` look identical to my other `<TextInput>`'s in my form. How do I get rid of the border?

**Comment by Quintis1212** [comment]
Try inputContainerStyle={{borderWidth: 0}}

**Comment by snx-mfallon** [comment]
Try applying the style to flatListProps. This solved my issue
