### ISSUE TITLE
Suggestions list is not absolute positioned in Android

### ISSUE THREAD

**Issue by bexoss** [mrlaessig/react-native-autocomplete-input#35]
Hello, It seems to the **suggestions list not absolute positioned** or enough z-index in Android, so the list box won't shown over its outer view component. (the cursor gone to upside and list followed in specific outer height)

![222](https://cloud.githubusercontent.com/assets/12633102/25012249/d79f9076-20aa-11e7-8f43-ec6a850293f0.PNG)

Above light box is suggestions list box, it never shown long enough in Android... 

In iOS, working properly e.g it is shown over its outer view height as you can see in below.

<img width="329" alt="444" src="https://cloud.githubusercontent.com/assets/12633102/25012528/bd351cdc-20ab-11e7-8f01-11c184f9c968.png">

**Comment by codesinghanoop** [comment]
Did you found any solution for it ??....

**Comment by l-urence** [comment]
Did you try to put the autocomplete inside an [absolute positioned view](https://github.com/l-urence/react-native-autocomplete-input/#android) in Android?

**Comment by codesinghanoop** [comment]
In iOS, it's getting popover but in android, it's not getting popover. I mean in android the subviews are not coming out of the main view. please help. Thanks for the fast reply.

**Comment by l-urence** [comment]
Did you take a look at the readme? The [Android section](https://github.com/l-urence/react-native-autocomplete-input/#android) describes the issue with Android.

**Comment by codesinghanoop** [comment]
Suggestions are not displaying.. can you please help me out..

**Comment by l-urence** [comment]
On the weekend I try to figure out if I can implement something to make the use with Android easier but unfortunately, there is not a generic solution for both platforms at the moment. Meanwhile, take a look at the [Android example](https://github.com/l-urence/react-native-autocomplete-input/blob/master/example/Example.android.js) it implements a working solution.

**Comment by codesinghanoop** [comment]
I really appreciate your fast response, the way you keep on updating Readme.md so that no one get stuck in some feature and thank you so much for helping. I am so grateful to you.

**Comment by MythriJL** [comment]
Hey, I implemented the android example given in the readme but still, the problem is the same that is, the suggestions are getting displayed inside the text Input in android view. In IOS it just works perfectly.
