### ISSUE TITLE
InputContainerStyle borderBottomWidth not applied. 

### ISSUE THREAD

**Issue by bexoss** [mrlaessig/react-native-autocomplete-input#36]
in Android,

`inputContainerStyle={{ borderWidth: 0, borderBottomWidth: 1, borderBottomColor: 'red', }}`

This is not working properly. I can't see any border. 

But In iOS, I can see bottom border properly. 

Maybe there is something problem or Do I miss something? 

I have to use this but because of some issues I got in trouble.

**Comment by emmaielle** [comment]
no answer?
