### ISSUE TITLE
Is it possible to show the results list in a ScrollView?

### ISSUE THREAD

**Issue by cfkenandy** [mrlaessig/react-native-autocomplete-input#57]
Thanks for this awesome component! 
If I type something in the suggestion box and there a lot of results, the keyboard covers up the results. Is there a way to render the results list in a ScrollView or something like it? We would like to be able to scroll through the list and not have to type until the result renders above the keyboard without it covering it? Can I use onStartShouldSetResponder?  I'm not sure how to use it.

**Comment by naomipol** [comment]
I've tried setting the suggestion list's height to the remaining space on top of keyboard. It helped reduce the list size and I also could see a scroll indicator inside, but not able to scroll.
Do you have any idea how to make this work?
I believe it has something to do with the `onStartShouldSetResponder`, but have no idea how to use it...

Thanks!

**Comment by avesgit** [comment]
yes im interestiong too

**Comment by naomipol** [comment]
I've figured it out, in case it helps anyone...

First set a `maxHeight` and pass it through the `listStyle` prop. This will cause the result list to scroll, in case your autocomplete is not nested inside a `ScrollView`, like in my case.
In case it is, the list will not scroll according to this issue: https://github.com/facebook/react-native/issues/1966 .

To fix it you need to do the following:

Add the following code as a prop to the parent View which wraps the ScrollView
```
onStartShouldSetResponderCapture={() => {
    this.setState({ enableScrollViewScroll: true });
}}
```
Add `scrollEnabled={this.state.enableScrollViewScroll}` prop to the ScrollView

Add the following prop to the Autocomplete
```
onStartShouldSetResponderCapture={() => {
     this.setState({ enableScrollViewScroll: false });

    // you should hold a ref to the autocomplete (in this case called 'autocomplete' 
    // in order to access the ListView's ref

     if (this.autocomplete.resultList.scrollProperties.offset === 0 && 
         this.state.enableScrollViewScroll === false) {
       this.setState({ enableScrollViewScroll: true });
     }
 }}
```
This works very well on IOS and Android both, scrolls the ListView if the touch is on List and else it scrolls the ScrollView.

**Comment by cfkenandy** [comment]
@naomipol , Your max height solution worked great! Thank you so much! I didn't have my autocomplete nested in `ScrollView` .

**Comment by arminghm** [comment]
@naomipol When click on the TextInput for typing I face this issue:

> Cannot read property "scrollProperties" of null

That's because the resulsList of autoComplete is null.
I added another condition to check that the resultList is not null: 
`if (this.refs.autoComplete.resultList !== null &&
                                        this.refs.autoComplete.resultList.scrollProperties.offset === 0 &&
                                        this.state.enableScrollViewScroll === false) {
                                        this.setState({enableScrollViewScroll: true});
                                    }`

but it only gets the scroll for the first time,  after first scroll I can not have the scroll on the resultList and it scroll the parent scrollView.

Do you have any Idea about this?

**Comment by hirani89** [comment]
@cfkenandy Can you please share your code as you mention that you do not have to `AutoComplete` in a `ScrollView`. When I put my `AutoComplete` in a `ScrollView`, the list does not show.

Regards,

**Comment by khushboogupta1** [comment]
@naomipol  can you please share your entire code as i am new to react native and not getting "refs" thing. Or my issue is posted [here](https://stackoverflow.com/questions/50699285/react-native-listview-not-scrolling-to-bottom-of-screen-in-ios-only) please have a look and provide me a fix. Thank you in advance.

**Comment by TonnelierFlorian** [comment]
@naomipol , Your maxHeight solution worked great on iOS but the list is still not scrollable on Android, do you have any idea about the reason ? Thanks !

**Comment by FAIZVEK** [comment]
How to put item name on input box and suggestion box hide ?

**Comment by paveltar** [comment]
> @naomipol When click on the TextInput for typing I face this issue:
> 
> > Cannot read property "scrollProperties" of null
> 
> That's because the resulsList of autoComplete is null.
> I added another condition to check that the resultList is not null:
> `if (this.refs.autoComplete.resultList !== null && this.refs.autoComplete.resultList.scrollProperties.offset === 0 && this.state.enableScrollViewScroll === false) { this.setState({enableScrollViewScroll: true}); }`
> 
> but it only gets the scroll for the first time, after first scroll I can not have the scroll on the resultList and it scroll the parent scrollView.
> 
> Do you have any Idea about this?

What's the solution for this problem now with resultList is an instance of FlatList which does not have scrollProperties?

**Comment by FauricioValencia** [comment]
Yeah, just need to add `listStyle`  with the styles :`{maxHeight:350}`  to `<Autocomplete/>`
something like this: 
`<Autocomplete listStyle={{maxHeight:350}} />`
