### ISSUE TITLE
Crash on Android 4.4.4 with long list

### ISSUE THREAD

**Issue by edmofro** [mrlaessig/react-native-autocomplete-input#60]
This is a very bizarre bug. In https://github.com/sussol/mobile we use your autocomplete input, but on earlier versions of Android it crashes under certain conditions:
- List of options is long
- Other scenes are rendered in the background

Unfortunately the crash is silent and sudden, and reveals no information about why it happened.

Through a long chain of trial and error, stripping back your code until the crash stopped happening, I found a very odd culprit. With everything else kept the same, it will stop crashing if you remove the `borderRadius` style for the `list` key within `androidStyles`. Madness!

In fact, passing through `borderRadius: 0` in the `listStyles` prop also works, so that's what we'll do for now, but you might like to remove borderRadius to avoid other users experiencing the same thing.

**Comment by amrita019** [comment]
Did you find a solution for this?
