### ISSUE TITLE
auto complete list  drop down list not shown on top in Android

### ISSUE THREAD

**Issue by pongponglau** [mrlaessig/react-native-autocomplete-input#61]
i use tabnavigator of react-navigation in my app. The autocomplete component is put as a header inside navigationOptions.

In iOS, the drop down list can show perfectly on top of the tab bar, but not in Android.

I have tried position: absolute and zIndex: 1 in the parent view of autocomplete. However, it does not help.

Thank you very much for your advice

**Comment by jlf123** [comment]
Any update on this issue?

**Comment by theGABS** [comment]
I have trouble with zIndex to.

As I understand - big trouble is that 
>The overflow style property defaults to hidden and cannot be changed on Android
So maybe you list just clipped by View

**Comment by ClaudiaHosu** [comment]
Any update on this, please? I have exactly the same issue with the autocomplete list being shown only as much as it's on top of the navbar, but it doesn't "overflow" it. I'm using the suggested absolutely positioned wrapper view.
