### ISSUE TITLE
Trigger event after populating auto-complete-input

### ISSUE THREAD

**Issue by AishwaryaSurana** [mrlaessig/react-native-autocomplete-input#62]
Can I trigger an event (_Eg: navigating to a new screen_) after the suggestion is selected and auto complete text is populated by that suggestion?

Right now I have to explicitly add a view component to navigate. Like,
`  <Button
        title="Show Calendar"
        onPress={
          () => this.gotopage()
        }/>
`

**Comment by cosydney** [comment]
+1

**Comment by cosydney** [comment]
@AishwaryaSurana  did you find another solution ?

**Comment by cosydney** [comment]
I did actually:

`<TouchableOpacity onPress={() => this._myrecord({query: label})}>
              <Text style={styles.itemText}>
                {label}
              </Text>
            </TouchableOpacity>` 

And then you can do whatever in your function: 
`
  _myrecord = (label) => {
    console.log(' --->', label.query)
    this.setState(label)
  }`
