### ISSUE TITLE
Autocomplete with remote filtering

### ISSUE THREAD

**Issue by pierol** [mrlaessig/react-native-autocomplete-input#70]
I don't know if this is an issue o a PR. In the example code the films are all loaded only one time when the component mount then it filters the list based on the query inserted in the input. This could be a good solution when you have a short list.  I came from the web so usual i filter the list on server side, i mean when the input change i make a new fetch with the new query and obtain the new list of results. How could i change the example code to get this behavior ?
I tried passing to the data propriety a method that make the fetch but i get an infinite loop. Is this way of use not correct ?

**Comment by l-urence** [comment]
Yes, you are right. Filtering should be done serverside. You can to a backend request after each button press and pass the result to the `data` prop.


This might give an idea (but not tested):

```
<AutoComplete 
  data={this.state.data}
  onChangeText={text =>
     fetch(`https://example.com?q=${text}`).then(data => this.setState({data))
  }
/>
```
