### ISSUE TITLE
Can't select with similar string result

### ISSUE THREAD

**Issue by fauzzi** [mrlaessig/react-native-autocomplete-input#73]
Hi,
I have issue with the similar string result, can't hide/close the list when I select the first record from suggestion. I attached the UI.
![iphone 6-7 2](https://user-images.githubusercontent.com/20034987/35141062-39269282-fd2c-11e7-9d10-ad146d8c9e51.png)

                            <Autocomplete
                                listStyle={{
                                margin : 0,
                                top : 0,
                                borderWidth: 1
                            }}
                                renderTextInput={this
                                ._renderTextInput
                                .bind(this)}
                                inputContainerStyle={{
                                borderWidth: 0,
                                height: styled.moderateScale(40)
                            }}
                                autoCapitalize="none"
                                autoCorrect={false}
                                containerStyle={styles.autocompleteContainer}
                                data={data.length === 1 && comp(query, data[0].styleID)
                                ? []
                                : data}
                                defaultValue={query}
                                onChangeText={text => this.setState({query: text})}
                                placeholder="Enter style ID"
                                renderItem={({styleDesc, styleID, customer}) => (

                                 <ScrollView keyboardShouldPersistTaps='always' >
                                    <TouchableOpacity
                                        onPress={this
                                        ._onStyleSelectedPress
                                        .bind(this, styleID, styleDesc, customer)}>
                                        <View style={styles.itemView}>
                                            <Text style={styles.itemText}>
                                                {styleID}                                            
                                            </Text>
                                        </View>
                                    </TouchableOpacity>
                              </ScrollView>
                            )}/>

**Comment by emannick** [comment]
Any update on this?

**Comment by l-urence** [comment]
To hide the suggestion list set `data` to `[]` if an item was selected. Or set the prop `hideReults={true}`.

**Comment by maartenvandillen** [comment]
setting data to [] does not close the results for me, setting hideResults to true does.

**Comment by shahrajk** [comment]
setting data to [] does not close the results for me also setting hideResults to true.
can you share your code @maartenvandillen

**Comment by maartenvandillen** [comment]
@shahrajk I can't remember what this was about, but reading my own and your comments seems we both have solved the issue, right?

**Comment by shahrajk** [comment]
no, both solution is not working for me. @maartenvandillen

**Comment by shahrajk** [comment]
<Autocomplete
                                autoCapitalize="none"
                                autoCorrect={false}
                                listStyle={{ position: 'relative' }}
                                containerStyle={styles.autocompleteContainer}
                                data={this.state.films}
                                defaultValue={query}
                                onChangeText={(text) => this.getLocalAddress(text)}
                                placeholder="Enter Star Wars film title"
                                renderItem={(films) => (
                                    <TouchableOpacity style={{ backgroundColor: 'white' }} onPress={() => this.setState({ query: films.item.value })}>
                                        <Text style={styles.itemText}>
                                            {films.item.value}
                                        </Text>
                                    </TouchableOpacity>
                                )}
                            />


this is my code can you tell me how I can do that. @maartenvandillen

**Comment by Javier-Rotelli** [comment]
hi @shahrajk i'm your code doesn't have the prop `hideResults` set. could that be the problem? 
also, what is being passed into data?

**Comment by maartenvandillen** [comment]
@shahrajk in my onChangeText handler I check for the right condition to close the dropdown. If it needs to be closed I do a setState on a boolean variable which is assigned to prop hideResults={!this.state.autocompleteOpen}

**Comment by bhaskardabhi** [comment]
I tried this and it worked. You can twist accordingly

```
    state = {
        query: '',
        open: true
    };

    render() {
        return (
            <Autocomplete
                hideResults={!this.state.open}
                onChangeText={text => this.setState({ query: text, open: true })}
                renderItem={item => (
                    <ListItem onPress={() => this.setState({ query: item, open: false })}>
                        <Text>{item}</Text>
                    </ListItem>
                )}
            />
        );
    }
```

**Comment by ahtisham09** [comment]
@mrlaessig  i am also facing same issue do you have any solution?
