### ISSUE TITLE
suggestion list is not rendering above INPUT TEXT

### ISSUE THREAD

**Issue by emannick** [mrlaessig/react-native-autocomplete-input#74]
Hi,

I'm using react-native-autocomplete-input.

I want my suggestion list is to render above INPUT TEXT.

How should I do that?

**Comment by l-urence** [comment]
There is just limited support for it right now. Please try to install [https://github.com/l-urence/react-native-autocomplete-input/tree/v3.6.0-rc](v3.6.0-rc) from npm. With `invertList={true}` the suggestion list should be rendered above the text input.

**Comment by EdwinJDiaz** [comment]
Hello, not working

![image](https://user-images.githubusercontent.com/11430535/60745142-99490900-9f3e-11e9-90b0-bb354b48ad80.png)

<Autocomplete
                  inputContainerStyle={styles.inputContainerStyle}
                  invertList={true}
                  autoCapitalize="none"
                  autoCorrect={false}
please, help !!
