### ISSUE TITLE
Styling issue after adding the Autocomplete Input.

### ISSUE THREAD

**Issue by Aravindhan12** [mrlaessig/react-native-autocomplete-input#77]
I have successfully implemented the Autocomplete input. But After adding the autocomplete text input, all other texts and buttons below the Autocomplete text input is moved to the end of the screen. When I tried by removing the Autocomplete Input from render, those texts and buttons are back to their normal position. 

Any ideas will be really helpful for me to overcome this issue ?

**Comment by impradeepsaini** [comment]
Same issue here..did you find any solution?

**Comment by Aravindhan12** [comment]
@impradeepsaini Yes I have fixed it by adding a separate view for the autocomplete text input with styles as mentioned in the document android section. It was clearly mentioned in the document android section and I have missed to have a look at first. I have read it again and again then fixed it by adding a separate  view for the autocomplete text input.

FOR EXAMPLE:

<View style={styles.autocompleteView}>
                <Autocomplete .....
</View>
<View>
    <Text>Any Texts..</Text>
</View>

**styles**
 autocompleteView: {
    flex: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 20,
    zIndex: 1
  }

Hope it will fix it for you too...
