### ISSUE TITLE
Cannot use two autocompletes in same component

### ISSUE THREAD

**Issue by ms-ak** [mrlaessig/react-native-autocomplete-input#82]
If I try to use two autocomplete text input component inside a screen, it doesn't work as expected. As both the autocomplete text box states are maintained in the screen component, setting value for one re-renders other one.

**Comment by l-urence** [comment]
Do you pass in the same data list?

**Comment by gitpushdev** [comment]
I'm using two auto complete in the same screen and no issues at all, choosing value from one auto complete does not affect the other one

**Comment by sam9010** [comment]
i have this error
my data is same but my data show in combo diffrent
