### ISSUE TITLE
Autocomplete TextInput overlaps other form elements

### ISSUE THREAD

**Issue by izikandrw** [mrlaessig/react-native-autocomplete-input#88]
Aloha from Hawaii--thanks for this library it's been great! I'm having an issue with layout. 

When using `Autocomplete` component it overlaps the other elements.
I am using `v3.5.0` of this library in a form on iOS:

this is a file where I define a component `DropdownFieldAutocomplete.js` that uses `Autocomplete` component. This is called in my main component which I posted farther down.
```
<View style={{flex: 1, zIndex: 1, position: 'relative'}}>
      <Autocomplete
        autoFocus={true}
        data={data}
        defaultValue={searchFieldValue}
        onChangeText={(text) => {
          onChangeText(text);
          input.onChange('');
        }
        }
        hideResults={hideResults}
        renderItem={(item) => (
          <TouchableOpacity
            key={item.value}
            style={{paddingTop: 7, paddingBottom: 7}}
            onPress={() => {
              input.onChange(item.value);
              onItemSelect(item.value);
              closeModal();
            }
            }>
            <Text style={{fontWeight: 'bold'}}>{item.header}</Text>
            <Text>{item.subTitle}</Text>
          </TouchableOpacity>
        )}
        renderSeparator={()=>(<ListSeparator />)}
        containerStyle={styles.autocompleteContainer}
        inputContainerStyle={styles.inputContainer}
        listStyle={styles.list}
      />
    </View>

const styles = StyleSheet.create({
    autocompleteContainer: {
      flex: 1,
      borderWidth: 0,
    },
    inputContainer: {
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 0,
      borderRightWidth: 0,
      marginRight: 5,
      marginLeft: 5,
    },
    textInput: {
      height: 50,
      padding: 7,
    },
    list: {
      paddingRight: 7,
      paddingLeft: 7,
      margin: 0,
      borderWidth: 0,
      maxHeight: 270, // necessary to make scrolling of list possible see:
      // https://github.com/l-urence/react-native-autocomplete-input/issues/57
    },
  });
```

main component that uses the DropdownFieldAutocomplete component which wraps `Autocomplete`
```
<Field
              name={'entityId'}
              component={DropdownFieldAutocomplete}
              validate={[required()]}
              data={entityList}
              onChangeText={(searchTerm) => searchEntities(searchTerm)}
              onItemSelect={(selectedEntityId)=> {
                selectEntity(selectedEntityId);
              }
              }
              hideResults={hideResults}
              searchFieldValue={selectedEntityName}
              onChange={() =>reset()}
              selectedValue={selectedEntityName}
            />
            <Field
              name={'entityForm'}
              component={Dropdown}
              validate={[required()]}
              data={formList}
              placeholder='Select the entity form...'
              selectedValue={selectedEntityFormName}
            />
```
You can see from screenshot below that the the `Autocomplete` component overlaps the second form field on the screen `entityForm`, the other components are visible (did not post their code)--it's as if the Autocomplete form is positioned absolutely and taken out of the flow of the page (even though I am NOT styling it absolutely anywhere). Setting a z-index at least brings it on top of the others but doesn't solve the problem that other components on the screen are being overlapped.

![img_b5f44a8fa8a4-1](https://user-images.githubusercontent.com/4181895/38584831-4e28781e-3cb3-11e8-8577-208f0b1aa9f2.jpeg)

**Comment by jsina** [comment]
I've get the keyboard's dimensions subtract from window's dimensions, then set this value to the `maxHeight` of `listStyle`

```
componentDidMount() {
    this.keyboardDidShowListener =
      Keyboard.addListener('keyboardDidShow', this._keyboardDidShow);
    this.keyboardDidHideListener =
      Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);
  }

 componentWillUnmount() {
    this.keyboardDidShowListener.remove();
    this.keyboardDidHideListener.remove();
  }

 _keyboardDidShow = (e) => {
    let listHeight =
      Dimensions.get('window').height - e.endCoordinates.height;
    this.setState({
      listHeight,
    });
  }


render() {
    const {
      listHeight,
    } = this.state;
    return (
      <AutocompleteNative
       ...
        listStyle={[styles.list, { maxHeight: listHeight }]}
      />
    );
  }
```

**Comment by vnd-ranga** [comment]
need to set maxHeight or height as Suggested by @jsina, or we can set the height on the item selected runtime with the condition. As I am using it with FlatListView in Android so set height which less than view

` <View style={styles.autocompleteContainer}>
                    <AutocompleteText
                        data={data}
                        defaultValue={query}
                        listStyle={{
                            maxHeight: 150,
                        }}
                        hideResults={hideResult}
                        onChangeText={text => this.setState({ query: text, hideResult: false })}
                        keyExtractor={(item, index) => (index.toString())}
                        renderItem={({ item }) => (
                            <TouchableOpacity
                                onPress={() => {
                                    var params = filterParams;
                                    params.vehicle_no = item.vehicle_registration_number
                                    this.setState({
                                        query: item.vehicle_registration_number,
                                        filterParams: params,
                                        hideResult: true,
                                    })
                                    this.getOrderList();
                                }}>
                                <Text style={{
                                }}>{item.vehicle_registration_number}</Text>
                            </TouchableOpacity>
                        )}
                    />
                </View>
const styles = StyleSheet.create({
    autocompleteContainer: {
        flex: 1,
        left: 10,
        position: 'absolute',
        right: 10,
        top: 5,
        height: "40%",
        zIndex: 1
    }
});`
